server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui
spring:
  datasource:
    url: jdbc:h2:file:./data/banco_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  profiles:
    active: dev
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
