apiVersion: v1
kind: Service
metadata:
  name: entidades-bancarias-api
  labels:
    app: entidades-bancarias-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: entidades-bancarias-api
